import Head from "next/head";
import Avatar from "../components/Avatar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Search Engine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* HEADER */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left  */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/* Icon */}
          {/* <ViewGridIcon /> */}
          <Avatar url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfM-pq4nauviZTexr2oGkeAgd6p0h_naPCKsBUUYCZOndzVRt60X2S9-EiOmwm--LRQ4k&usqp=CAU" />
        </div>
      </header>
      {/* BODY */}

      {/* FOOTER */}
    </div>
  );
}
